package pojo;

// Generated 18 Feb, 2023 5:04:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banner generated by hbm2java
 */
@Entity
@Table(name = "banner", catalog = "coza_store")
public class Banner implements java.io.Serializable {

	private Integer id;
	private String name;
	private String bimage;

	public Banner() {
	}

	public Banner(String name, String bimage) {
		this.name = name;
		this.bimage = bimage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "bimage", length = 200)
	public String getBimage() {
		return this.bimage;
	}

	public void setBimage(String bimage) {
		this.bimage = bimage;
	}

}
