package pojo;

// Generated 18 Feb, 2023 5:04:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "coza_store")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private Float contact;
	private String password;
	private String cpassword;
	private Set<Contact> contacts = new HashSet<Contact>(0);
	private Set<Shipping> shippings = new HashSet<Shipping>(0);
	private Set<Subscribe> subscribes = new HashSet<Subscribe>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

	public User() {
	}

	public User(String name, String email, Float contact, String password, String cpassword, Set<Contact> contacts,
			Set<Shipping> shippings, Set<Subscribe> subscribes, Set<Order> orders, Set<Cart> carts,
			Set<Wishlist> wishlists) {
		this.name = name;
		this.email = email;
		this.contact = contact;
		this.password = password;
		this.cpassword = cpassword;
		this.contacts = contacts;
		this.shippings = shippings;
		this.subscribes = subscribes;
		this.orders = orders;
		this.carts = carts;
		this.wishlists = wishlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact", precision = 12, scale = 0)
	public Float getContact() {
		return this.contact;
	}

	public void setContact(Float contact) {
		this.contact = contact;
	}

	@Column(name = "password", length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cpassword", length = 200)
	public String getCpassword() {
		return this.cpassword;
	}

	public void setCpassword(String cpassword) {
		this.cpassword = cpassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Shipping> getShippings() {
		return this.shippings;
	}

	public void setShippings(Set<Shipping> shippings) {
		this.shippings = shippings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Subscribe> getSubscribes() {
		return this.subscribes;
	}

	public void setSubscribes(Set<Subscribe> subscribes) {
		this.subscribes = subscribes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Wishlist> getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set<Wishlist> wishlists) {
		this.wishlists = wishlists;
	}

}
